name: CI/CD for Laravel

on:
  push:
    branches:
      - master  # Запускать при пушах в ветку master
  pull_request:
    branches:
      - master  # Запускать при пулл-запросах на ветку master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Настроим PostgreSQL контейнер
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-timeout=30s --health-retries=3

    steps:
      # Шаг 1: Проверка исходного кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Укажите нужную версию PHP
          extensions: mbstring, bcmath, xml, ctype, json, gd, pdo, pdo_pgsql

      # Шаг 3: Установка зависимостей через Composer
      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction --prefer-dist --optimize-autoloader

      # Шаг 4: Копирование .env и настройка конфигурации
      - name: Set up .env file
        run: |
          cp .env.example .env
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=pgsql/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=homestead/DB_DATABASE=laravel_test/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=postgres/' .env
          sed -i 's/DB_PASSWORD=secret/DB_PASSWORD=root/' .env

      # Шаг 5: Применение миграций
      - name: Run migrations
        run: |
          php artisan key:generate
          php artisan migrate

      # Шаг 6: Запуск тестов
      - name: Run tests
        run: |
          vendor/bin/phpunit --coverage-text

      # Шаг 7: Развертывание (например, через SSH или другой сервер)
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          # Пример деплоя через SSH (поменяйте на свой путь деплоя)
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd /path/to/your/project && git pull origin main && composer install && php artisan migrate"
